---

- name: Configuring Minecraft server
  gather_facts: false
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
  - name: Add minecraft user to run server processes
    ansible.builtin.user:
      name: minecraft
      comment: "Minecraft user"
      shell: /bin/bash
      password: $6$1DSFb9V1gLzczV83$EUOf3EOxxIGl3h51ci2vS8boj.Wr6FSvXkbShbR3.swCwdVXqYw4/mtEepfI8SSVSz1nsOPK14i7xNhdQ/Das.


  - name: Allow password authentication to the server
    lineinfile: 
      dest: /etc/ssh/sshd_config 
      regexp: "^PasswordAuthentication" 
      line: "PasswordAuthentication yes" 
      state: present
    notify:
      - restart sshd

  - name: Install docker-compose to run the Minecraft server container
    apt:
      name: docker-compose
      state: present

  - name: Copy Minecraft server files over to VM
    ansible.builtin.copy:
      src: ./minecraft/
      dest: ~minecraft/minecraft-server
      owner: minecraft
      group: minecraft

  - name: Run Minecraft server via docker-compose
    community.docker.docker_compose:
      project_src: ~minecraft/minecraft-server
    register: output

  - ansible.builtin.debug:
      var: output

  handlers:
  - name: restart sshd
    service:
      name: sshd
      state: restarted

